package com.thebrokenrail.gestus.client;

import com.thebrokenrail.gestus.Gestus;
import net.fabricmc.api.ClientModInitializer;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.fabricmc.fabric.api.client.rendereregistry.v1.EntityRendererRegistry;
import net.minecraft.client.render.entity.ArmorStandEntityRenderer;

@Environment(EnvType.CLIENT)
public class GestusClient implements ClientModInitializer {
    @Override
    public void onInitializeClient() {
        EntityRendererRegistry.INSTANCE.register(Gestus.FAKE_PLAYER_ENTITY_TYPE, (dispatcher, context) -> new ArmorStandEntityRenderer(dispatcher));
    }
}
